# Generated by Django 5.1.7 on 2025-06-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
