# Generated by Django 5.1.7 on 2025-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
